version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION:-8.11.1}
    command: >
      /bin/sh -c "(./bin/elasticsearch-plugin list | grep -q ingest-attachment || ./bin/elasticsearch-plugin install --batch ingest-attachment) && /usr/local/bin/docker-entrypoint.sh"
    environment:
      node.name: elasticsearch
      cluster.name: es-docker-cluster
      cluster.initial_master_nodes: elasticsearch
      discovery.seed_hosts: elasticsearch
      bootstrap.memory_lock: 'true'
      xpack.security.enabled: 'false'
      action.destructive_requires_name: 'false'
      indices.id_field_data.enabled: 'true'
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      path.repo: /usr/share/elasticsearch/repository
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - esrepo:/usr/share/elasticsearch/repository
    ports:
      - 9200:9200
    networks:
      - elastic
volumes:
  data01:
  data02:
  esrepo:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1000,gid=0"

networks:
  elastic:
    driver: bridge
